import { expect, test } from "@playwright/test";
import { nanoid } from "nanoid";
import { createNotesFixture } from "./fixtures/notes";
import { authCookieHeader, getE2eSql, playwrightAuthCookies } from "./fixtures/db";

const captureText = "Cookie and Ferg are already sorting out train coverage. This is urgent.";

test("interpretation requires opt-in and an explicit idempotent save creates only selected private tasks", async ({ request }) => {
  const { author, peer, alliance } = await createNotesFixture("officer");
  const headers = { Cookie: authCookieHeader(author) };
  const peerHeaders = { Cookie: authCookieHeader(peer) };
  const input = { draftId: nanoid(), body: captureText, revision: 1, overrideRevision: 0, locale: "en-US" };
  const denied = await request.post("/api/notes/intake/interpret", { headers, data: input });
  expect(denied.status()).toBe(403);
  const preference = await (await request.get("/api/notes/intake/preferences", { headers })).json();
  expect(preference.configured).toBe(true);
  const enabled = await request.put("/api/notes/intake/preferences", { headers, data: { enabled: true, expectedVersion: preference.version } });
  expect(enabled.status()).toBe(200);
  const interpretation = await request.post("/api/notes/intake/interpret", { headers, data: input });
  expect(interpretation.status(), await interpretation.text()).toBe(200);
  const { result } = await interpretation.json();
  expect(result.actions).toHaveLength(1);
  expect(result.actions[0]).toMatchObject({ status: "in_progress", priority: "urgent" });
  expect(result.body).toBeUndefined();
  expect((await (await request.get("/api/notes/tasks", { headers })).json()).tasks).toHaveLength(0);
  const data = { requestId: nanoid(), title: "Private capture", body: captureText, tasks: result.actions.map((item: Record<string, unknown>) => ({ ...item, dueAt: "2026-01-01T12:00:00Z" })) };
  const first = await request.post("/api/notes/capture", { headers, data });
  expect(first.status(), await first.text()).toBe(200);
  const saved = await first.json();
  expect(saved.taskIds).toHaveLength(1);
  const repeated = await request.post("/api/notes/capture", { headers, data });
  expect(repeated.status()).toBe(200);
  expect((await repeated.json()).taskIds).toEqual(saved.taskIds);
  const mismatch = await request.post("/api/notes/capture", { headers, data: { ...data, body: "Different request" } });
  expect(mismatch.status()).toBe(409);
  const id = saved.taskIds[0];
  const beforeShare = await request.get(`/api/notes/tasks/${id}`, { headers: peerHeaders });
  expect(beforeShare.status()).toBe(404);
  const oldList = await request.get("/api/officer-intel/action-items", { headers: peerHeaders });
  expect(oldList.status()).toBe(200);
  expect((await oldList.json()).items).toHaveLength(0);
  const oldEdit = await request.patch(`/api/officer-intel/action-items/${id}`, { headers: peerHeaders, data: { status: "done" } });
  expect(oldEdit.status()).toBe(404);
  const inboxBefore = await request.get("/api/inbox/reminders", { headers: peerHeaders });
  expect(inboxBefore.status()).toBe(200);
  expect((await inboxBefore.json()).items.some((item: { resourceId: string }) => item.resourceId === id)).toBe(false);
  const share = await (await request.get(`/api/notes/tasks/${id}/sharing`, { headers })).json();
  const shared = await request.put(`/api/notes/tasks/${id}/sharing`, { headers, data: { expectedVersion: share.version, grants: [{ subjectKind: "user", subjectId: peer.hqUserId, role: "read" }] } });
  expect(shared.status()).toBe(200);
  const peerTask = await request.get(`/api/notes/tasks/${id}`, { headers: peerHeaders });
  expect(peerTask.status()).toBe(200);
  expect((await peerTask.json()).task.source).toBeNull();
  expect((await request.get(`/api/notes/${saved.noteId}`, { headers: peerHeaders })).status()).toBe(404);
  expect((await request.get(`/api/notes/${saved.noteId}/history`, { headers: peerHeaders })).status()).toBe(404);
  const sql = getE2eSql();
  const [count] = await sql`SELECT count(*)::int AS count FROM officer_action_items WHERE alliance_id = ${alliance.allianceId}`;
  expect(count.count).toBe(1);
});

test("automatic intake previews preserve manual None and task status, and never resynchronize saved work from source edits", async ({ page }) => {
  const { author } = await createNotesFixture();
  await page.context().addCookies(playwrightAuthCookies(author));
  await page.goto("/notes");
  await page.getByRole("button", { name: "New note", exact: true }).first().click();
  const dialog = page.getByRole("dialog", { name: "New note", exact: true });
  await dialog.getByLabel("Note", { exact: true }).fill(captureText);
  const interpreted = page.waitForResponse((response) => response.url().endsWith("/api/notes/intake/interpret") && response.status() === 200);
  await dialog.getByRole("checkbox", { name: "Suggest tasks from my captures", exact: true }).check();
  await interpreted;
  const preview = dialog.getByTestId("intake-task");
  await expect(preview).toHaveCount(1);
  await preview.getByRole("button", { name: "Status", exact: true }).click();
  await dialog.getByRole("option", { name: "Backlog", exact: true }).click();
  await dialog.locator("aside").getByLabel("Priority", { exact: true }).selectOption("none");
  await expect(dialog.locator("aside").getByLabel("Priority", { exact: true })).toHaveValue("none");
  await dialog.getByRole("button", { name: "Save note and 1 task", exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole("button", { name: "Tasks", exact: true }).click();
  const task = page.getByTestId("note-task");
  await expect(task).toContainText("Sort out train coverage");
  const listed = await (await page.request.get("/api/notes/tasks")).json();
  expect(listed.tasks[0]).toMatchObject({ status: "open", priority: "urgent" });
  const sourceId = listed.tasks[0].source.id;
  const source = await (await page.request.get(`/api/notes/${sourceId}`)).json();
  expect(source.note.priority).toBeNull();
  const moved = await page.request.patch(`/api/notes/tasks/${listed.tasks[0].id}`, { data: { expectedVersion: listed.tasks[0].version, status: "done" } });
  expect(moved.status()).toBe(200);
  const edited = await page.request.patch(`/api/notes/${sourceId}`, { data: { expectedVersion: source.note.version, body: "Still considering the next step" } });
  expect(edited.status()).toBe(200);
  const after = await (await page.request.get(`/api/notes/tasks/${listed.tasks[0].id}`)).json();
  expect(after.task.status).toBe("done");
});

test("assignment requires deliberate task-only access and cross-alliance capture rolls back", async ({ request }) => {
  const { author, peer } = await createNotesFixture();
  const other = await createNotesFixture();
  const headers = { Cookie: authCookieHeader(author) };
  const missingShare = await request.post("/api/notes/tasks", { headers, data: { title: "Confirm roster", assigneeHqUserId: peer.hqUserId } });
  expect(missingShare.status()).toBe(409);
  expect((await missingShare.json()).code).toBe("assignee_access");
  const assigned = await request.post("/api/notes/tasks", { headers, data: { title: "Confirm roster", assigneeHqUserId: peer.hqUserId, shareWithAssignee: true } });
  expect(assigned.status()).toBe(200);
  const task = (await assigned.json()).task;
  expect((await request.get(`/api/notes/tasks/${task.id}`, { headers: { Cookie: authCookieHeader(peer) } })).status()).toBe(200);
  const invalid = await request.post("/api/notes/capture", { headers, data: { requestId: nanoid(), body: "Cannot link across alliances", memberIds: [other.cookie.ashedMemberId], tasks: [{ actionKey: "one", title: "Do work", included: true, evidence: null }] } });
  expect(invalid.status()).toBe(400);
  const notes = await (await request.get("/api/notes", { headers })).json();
  expect(notes.notes).toHaveLength(0);
  const tasks = await (await request.get("/api/notes/tasks", { headers })).json();
  expect(tasks.tasks).toHaveLength(1);
});
