import { expect, test } from "@playwright/test";
import { nanoid } from "nanoid";
import { authCookieHeader, getE2eSql } from "./fixtures/db";
import { createNotesFixture } from "./fixtures/notes";
import { playwrightAuthCookies } from "./fixtures/auth";

test("workspace search scopes notes, tasks and committed source evidence before pagination", async ({ request, page }) => {
  const { author, peer, alliance } = await createNotesFixture("officer");
  const headers = { Cookie: authCookieHeader(author) };
  const other = { Cookie: authCookieHeader(peer) };
  const noteId = (await (await request.post("/api/notes", { headers, data: { title: "Orbit strategy", body: `Private analysis token=example-unsearchable ${"1".repeat(14)}`, documentType: "meeting", keyDecisions: ["Orbit decision"] } })).json()).noteId;
  await request.post("/api/notes/tasks", { headers, data: { requestId: nanoid(), title: "Orbit follow-up", status: "open" } });
  const sql = getE2eSql();
  const sourceId = nanoid();
  await sql`INSERT INTO officer_chat_sessions (id, alliance_id, title, status, created_by_hq_user_id) VALUES (${sourceId}, ${alliance.allianceId}, 'Historical source', 'imported', ${author.hqUserId})`;
  await sql`INSERT INTO officer_chat_messages (id, session_id, alliance_id, sender_name, original_text, locale_text, locale_code, sequence_order, source_image_index) VALUES (${nanoid()}, ${sourceId}, ${alliance.allianceId}, NULL, 'Orbit discussion', 'Orbit discussion', 'und', 0, NULL)`;
  const own = await request.get("/api/notes/search?q=Orbit", { headers });
  expect(own.status()).toBe(200);
  const result = await own.json();
  expect(new Set(result.results.map((row: { kind: string }) => row.kind))).toEqual(new Set(["note", "task", "source"]));
  expect((await (await request.get("/api/notes/search?q=Orbit&limit=1", { headers: other })).json()).results).toEqual([]);
  await sql`INSERT INTO knowledge_resource_grants (id, resource_id, alliance_id, subject_kind, subject_id, role) VALUES (${nanoid()}, ${`note:${noteId}`}, ${alliance.allianceId}, 'user', ${peer.hqUserId}, 'read')`;
  const shared = await (await request.get("/api/notes/search?q=Orbit", { headers: other })).json();
  expect(shared.results.map((row: { id: string }) => row.id)).toEqual([noteId]);
  const clause = await (await request.get("/api/notes/search?q=decision", { headers })).json();
  expect(clause.results.some((row: { id: string }) => row.id === noteId)).toBe(true);
  expect((await request.get("/api/notes/search?q=Orbit")).status()).toBe(401);
  expect((await (await request.get("/api/notes/search?q=example-unsearchable", { headers })).json()).results).toEqual([]);
  expect((await (await request.get(`/api/notes/search?q=${"1".repeat(14)}`, { headers })).json()).results).toEqual([]);
  expect((await (await request.get("/api/notes/search?q=token=example-unsearchable", { headers })).json()).results).toEqual([]);
  expect(JSON.stringify(result)).not.toContain("example-unsearchable");
  const bootstrap = await request.get("/api/auth/bootstrap?next=/", { maxRedirects: 0 });
  expect(bootstrap.status()).toBeGreaterThanOrEqual(300);
  expect(bootstrap.status()).toBeLessThan(400);
  const setCookie = bootstrap.headers()["set-cookie"] ?? "";
  const bootstrapSession = /alliance_hq_session=([^;]+)/.exec(Array.isArray(setCookie) ? setCookie.join(";") : setCookie)?.[1];
  expect(bootstrapSession).toBeTruthy();
  expect((await request.get("/api/notes/search?q=Orbit", { headers: { Cookie: `alliance_hq_session=${bootstrapSession}` } })).status()).toBe(403);
  const largeId = nanoid();
  await sql`INSERT INTO performance_notes (id, alliance_id, kind, intake_mode, source, created_by_hq_user_id, body) VALUES (${largeId}, ${alliance.allianceId}, 'note', 'thought', 'web', ${author.hqUserId}, ${"older history ".repeat(30_000) + "RareMarker"})`;
  expect((await (await request.get("/api/notes/search?q=RareMarker", { headers })).json()).results.map((row: { id: string }) => row.id)).toEqual([largeId]);
  await page.context().addCookies(playwrightAuthCookies(author));
  await page.goto("/notes?view=search");
  const panel = page.getByTestId("notes-search");
  await panel.getByLabel("Search terms", { exact: true }).fill("Orbit");
  await panel.getByRole("button", { name: "Search", exact: true }).click();
  await expect(panel.getByRole("heading", { name: "Orbit strategy", exact: true })).toBeVisible();
});
