import { expect, test } from "@playwright/test";
import { authCookieHeader, playwrightAuthCookies } from "./fixtures/db";
import { createNotesFixture as fixture } from "./fixtures/notes";

test("captures and edits notes with stable manual member exclusions and nullable priority", async ({ page }) => {
  const { author, cookie, ferg } = await fixture();
  await page.context().addCookies(playwrightAuthCookies(author));
  await page.goto("/notes");
  await expect(page.getByTestId("notes-workspace")).toBeVisible();
  await page.getByRole("button", { name: "New note", exact: true }).first().click();
  let dialog = page.getByRole("dialog");
  await dialog.getByLabel("Title", { exact: true }).fill("Rally coverage");
  await dialog.getByLabel("Note", { exact: true }).fill("Cookie and Ferg will check our rally coverage.");
  await expect(dialog.getByRole("button", { name: "Unlink Cookie", exact: true })).toBeVisible();
  await dialog.getByRole("button", { name: "Unlink Ferg", exact: true }).click();
  await dialog.getByLabel("Priority", { exact: true }).selectOption("urgent");
  await dialog.getByLabel("Labels", { exact: true }).fill("Rallies, Coverage");
  await dialog.getByLabel("Notebook", { exact: true }).fill("Private strategy");
  await dialog.getByRole("button", { name: "Save note", exact: true }).click();
  await expect(dialog).not.toBeVisible();
  const card = page.getByTestId("note-card").filter({ hasText: "Rally coverage" });
  await expect(card).toBeVisible();
  await expect(card).toContainText("Urgent");
  const noteId = await card.getAttribute("data-note-id");
  await card.getByRole("button").first().click();
  dialog = page.getByRole("dialog");
  await dialog.getByRole("button", { name: "Write", exact: true }).click();
  await dialog.getByLabel("Note", { exact: true }).fill("Cookie and Ferg will check our rally coverage. Updated details.");
  await expect(dialog.getByRole("button", { name: "Unlink Ferg", exact: true })).toHaveCount(0);
  await dialog.getByLabel("Priority", { exact: true }).selectOption("none");
  await dialog.getByRole("button", { name: "Save note", exact: true }).click();
  await expect(dialog).not.toBeVisible();
  const response = await page.request.get(`/api/notes/${noteId}`);
  expect(response.status()).toBe(200);
  const { note } = await response.json();
  expect(note.priority).toBeNull();
  expect(note.members.map((member: { ashedMemberId: string }) => member.ashedMemberId)).toEqual([cookie.ashedMemberId]);
  expect(note.excludedMemberIds).toContain(ferg.ashedMemberId);
  expect(note.source).toBe("web");
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(card).toBeVisible();
  await card.getByRole("button").first().click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await expect(page.getByRole("dialog").getByRole("button", { name: "Close", exact: true }).last()).toBeInViewport();
});

test("shares current content without private organization or history and honors revocation", async ({ page, browser }) => {
  const { author, peer } = await fixture();
  await page.context().addCookies(playwrightAuthCookies(author));
  const created = await page.request.post("/api/notes", { data: { title: "Shared rally brief", body: "First private version", notebook: "Private strategy" } });
  expect(created.status()).toBe(200);
  const { noteId, notes } = await created.json();
  const saved = notes.find((note: { id: string }) => note.id === noteId);
  const edited = await page.request.patch(`/api/notes/${noteId}`, { data: { expectedVersion: saved.version, body: "Current shareable brief" } });
  expect(edited.status()).toBe(200);
  await page.goto("/notes");
  const card = page.getByTestId("note-card").filter({ hasText: "Shared rally brief" });
  await card.getByRole("button", { name: "Share", exact: true }).click();
  const sharing = page.getByRole("dialog", { name: "Share note", exact: true });
  await sharing.getByLabel("Add people", { exact: true }).selectOption(peer.hqUserId);
  await sharing.getByRole("button", { name: "Save sharing", exact: true }).click();
  await expect(sharing).not.toBeVisible();
  const peerContext = await browser.newContext();
  await peerContext.addCookies(playwrightAuthCookies(peer));
  const reader = await peerContext.newPage();
  await reader.goto("/notes");
  await reader.getByRole("button", { name: /^Shared with me/ }).click();
  const sharedCard = reader.getByTestId("note-card").filter({ hasText: "Shared rally brief" });
  await expect(sharedCard).toBeVisible();
  await sharedCard.getByRole("button").first().click();
  const preview = reader.getByRole("dialog");
  await expect(preview).toContainText("Current shareable brief");
  await expect(preview).not.toContainText("Private strategy");
  await expect(preview.getByRole("button", { name: "Save note", exact: true })).toHaveCount(0);
  const history = await reader.request.get(`/api/notes/${noteId}/history`);
  expect(history.status()).toBe(404);
  const peerEdit = await reader.request.patch(`/api/notes/${noteId}`, { data: { expectedVersion: 3, body: "Not allowed" } });
  expect(peerEdit.status()).toBe(404);
  const state = await (await page.request.get(`/api/notes/${noteId}/sharing`)).json();
  const revoked = await page.request.put(`/api/notes/${noteId}/sharing`, { data: { expectedVersion: state.version, grants: [] } });
  expect(revoked.status()).toBe(200);
  await reader.evaluate(() => window.dispatchEvent(new Event("focus")));
  await expect(preview).not.toBeVisible();
  await expect(reader.getByTestId("note-card")).toHaveCount(0);
  await peerContext.close();
});

test("keeps stale edits from overwriting a saved note and rejects cross-alliance member associations atomically", async ({ request }) => {
  const { author } = await fixture();
  const other = await fixture();
  const headers = { Cookie: authCookieHeader(author) };
  const created = await request.post("/api/notes", { headers, data: { title: "Version safety", body: "Original" } });
  expect(created.status()).toBe(200);
  const { noteId, notes } = await created.json();
  const version = notes.find((note: { id: string }) => note.id === noteId).version;
  const first = await request.patch(`/api/notes/${noteId}`, { headers, data: { expectedVersion: version, body: "Saved update" } });
  expect(first.status()).toBe(200);
  const stale = await request.patch(`/api/notes/${noteId}`, { headers, data: { expectedVersion: version, body: "Stale overwrite" } });
  expect(stale.status()).toBe(409);
  const invalid = await request.post("/api/notes", { headers, data: { title: "Must roll back", body: "Not saved", memberIds: [other.cookie.ashedMemberId] } });
  expect(invalid.status()).toBe(400);
  const listed = await (await request.get("/api/notes", { headers })).json();
  expect(listed.notes.some((note: { title: string }) => note.title === "Must roll back")).toBe(false);
  const current = await (await request.get(`/api/notes/${noteId}`, { headers })).json();
  expect(current.note.body).toBe("Saved update");
  expect(current.note.title).toBe("Version safety");
  const history = await (await request.get(`/api/notes/${noteId}/history`, { headers })).json();
  expect(history.revisions).toHaveLength(1);
  expect(history.revisions[0].snapshot.body).toBe("Original");
  const restored = await request.patch(`/api/notes/${noteId}`, { headers, data: { ...history.revisions[0].snapshot, expectedVersion: current.note.version } });
  expect(restored.status()).toBe(200);
  expect((await restored.json()).note.body).toBe("Original");
  const retained = await (await request.get(`/api/notes/${noteId}/history`, { headers })).json();
  expect(retained.revisions).toHaveLength(2);
});

test("supports localized capture and page-scoped keyboard actions", async ({ page }) => {
  const { author } = await fixture();
  await page.context().addCookies(playwrightAuthCookies(author));
  await page.goto("/pt-BR/notes");
  await expect(page.getByRole("heading", { name: "Notas", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Nova nota", exact: true }).first().click();
  await page.getByRole("dialog").getByRole("button", { name: "Fechar", exact: true }).last().click();
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await page.keyboard.press("Alt+n");
  const dialog = page.getByRole("dialog", { name: "Nova nota", exact: true });
  await expect(dialog).toBeVisible();
  await dialog.getByLabel("Título", { exact: true }).fill("Registro da aliança");
  await dialog.getByLabel("Nota", { exact: true }).fill("Uma observação para consultar depois.");
  await dialog.getByRole("button", { name: "Salvar nota", exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByTestId("note-card")).toContainText("Registro da aliança");
  await page.keyboard.press("/");
  await expect(page.getByRole("searchbox", { name: "Buscar nas suas notas…", exact: true })).toBeFocused();
});
