import { expect, test } from "@playwright/test";
import { nanoid } from "nanoid";
import { authCookieHeader, getE2eSql } from "./fixtures/db";
import { createNotesFixture } from "./fixtures/notes";
import { playwrightAuthCookies } from "./fixtures/auth";

test("legacy meeting routes and canonical notes share content, approval, and immutable history", async ({ page }) => {
  const { author, peer, alliance } = await createNotesFixture("officer");
  const sql = getE2eSql();
  const sourceId = nanoid(), legacyId = nanoid(), taskId = nanoid();
  await sql`INSERT INTO officer_chat_sessions (id, alliance_id, title, created_by_hq_user_id) VALUES (${sourceId}, ${alliance.allianceId}, 'Private source title', ${author.hqUserId})`;
  await sql`INSERT INTO officer_meeting_notes (id, alliance_id, session_id, summary, key_decisions, open_questions, status, synthesized_by_hq_user_id, approved_by_hq_user_id, approved_at) VALUES (${legacyId}, ${alliance.allianceId}, ${sourceId}, 'Original summary', '["Original decision"]', '["Original question"]', 'approved', ${author.hqUserId}, ${author.hqUserId}, now())`;
  await sql`INSERT INTO officer_action_items (id, alliance_id, note_id, session_id, title, status, priority, created_by_hq_user_id, completed_at) VALUES (${taskId}, ${alliance.allianceId}, ${legacyId}, ${sourceId}, 'Accepted work', 'done', 'high', ${author.hqUserId}, now())`;
  const headers = { Cookie: authCookieHeader(author) };
  const oldPath = `/api/officer-intel/notes/${legacyId}`;
  const legacy = (await (await page.request.get(oldPath, { headers })).json()).note;
  expect(legacy.canonicalNoteId).toBe(`meeting:${legacyId}`);
  const path = `/api/notes/${legacy.canonicalNoteId}`;
  const canonical = (await (await page.request.get(path, { headers })).json()).note;
  expect(canonical).toMatchObject({ body: "Original summary", documentType: "meeting", keyDecisions: ["Original decision"], openQuestions: ["Original question"] });
  expect((await page.request.get(path, { headers: { Cookie: authCookieHeader(peer) } })).status()).toBe(404);
  expect((await page.request.patch(path, { headers, data: { expectedVersion: canonical.version, body: "Canonical edit" } })).status()).toBe(200);
  const edited = (await (await page.request.get(oldPath, { headers })).json()).note;
  expect(edited).toMatchObject({ summary: "Canonical edit", keyDecisions: ["Original decision"], status: "draft" });
  expect((await page.request.put(oldPath, { headers, data: { expectedVersion: legacy.version, summary: "Stale edit" } })).status()).toBe(409);
  expect((await page.request.put(oldPath, { headers, data: { expectedVersion: edited.version, summary: "Legacy adapter edit", keyDecisions: ["Reviewed decision"], approve: true } })).status()).toBe(200);
  const latest = (await (await page.request.get(path, { headers })).json()).note;
  expect(latest).toMatchObject({ body: "Legacy adapter edit", keyDecisions: ["Reviewed decision"], openQuestions: ["Original question"] });
  const [frozen] = await sql`SELECT summary, key_decisions, resource_id, canonical_note_id FROM officer_meeting_notes WHERE id = ${legacyId}`;
  expect(frozen).toMatchObject({ summary: "Original summary", key_decisions: ["Original decision"], resource_id: `meeting:${legacyId}`, canonical_note_id: legacy.canonicalNoteId });
  const [task] = await sql`SELECT status, priority, source_note_id, completed_at FROM officer_action_items WHERE id = ${taskId}`;
  expect(task).toMatchObject({ status: "done", priority: "high", source_note_id: legacy.canonicalNoteId });
  expect(task.completed_at).not.toBeNull();
  await expect(sql`UPDATE officer_meeting_notes SET summary = 'Forbidden second writer' WHERE id = ${legacyId}`).rejects.toThrow();
  const history = await (await page.request.get(`${path}/history`, { headers })).json();
  expect(JSON.stringify(history)).toContain("Canonical edit");
  const draftId = nanoid();
  const savedDraft = await page.request.put(`/api/notes/drafts/${draftId}`, { headers, data: { expectedVersion: 0, sourceNoteId: latest.id, sourceVersion: latest.version, state: { fields: { title: latest.title, body: "Older-client body edit" } } } });
  expect(savedDraft.status()).toBe(200);
  const draft = await savedDraft.json();
  expect((await page.request.post("/api/notes/capture", { headers, data: { body: "Older-client body edit", draftId, expectedDraftVersion: draft.version, requestId: nanoid() } })).status()).toBe(200);
  expect((await (await page.request.get(path, { headers })).json()).note).toMatchObject({ documentType: "meeting", keyDecisions: ["Reviewed decision"], openQuestions: ["Original question"] });
  await page.context().addCookies(playwrightAuthCookies(author));
  await page.goto(`/officer-intel/notes/${legacyId}`);
  await page.getByRole("link", { name: "Open in Notes", exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`/notes/meeting(?::|%3A)${legacyId}$`));
  await expect(page.getByText("Reviewed decision", { exact: true })).toBeVisible();
  const editor = page.getByRole("dialog");
  await editor.getByRole("button", { name: "Write", exact: true }).click();
  await editor.getByLabel("Key decisions 1", { exact: true }).fill("Browser decision");
  await editor.getByRole("button", { name: "Save note", exact: true }).click();
  await expect(editor).not.toBeVisible();
  expect((await (await page.request.get(oldPath, { headers })).json()).note).toMatchObject({ keyDecisions: ["Browser decision"], status: "draft" });
});
