import type { LucideIcon } from "lucide-react";
import {
  BarChart3,
  Bot,
  ClipboardCheck,
  ClipboardList,
  Database,
  ExternalLink,
  FileText,
  Flame,
  GitMerge,
  GraduationCap,
  Handshake,
  LayoutDashboard,
  LifeBuoy,
  ListChecks,
  Mountain,
  Settings,
  Shield,
  Skull,
  Star,
  Syringe,
  Train,
  TreePalm,
  MapPinned,
  Upload,
  UserCog,
  Users,
  Wallet,
  Zap,
} from "lucide-react";

/** Unique lucide icon per sidebar nav page id */
export const NAV_PAGE_ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  alliances: Handshake,
  members: Users,
  "waiting-list": ClipboardList,
  "alliance-tasks": ListChecks,
  "merge-manager": GitMerge,
  professions: GraduationCap,
  "vs-performance": BarChart3,
  donations: Wallet,
  "alliance-exercise": Flame,
  reports: FileText,
  "viral-resistance": Shield,
  "my-vr": Syringe,
  "my-thp": Zap,
  trains: Train,
  "battle-plan": MapPinned,
  "desert-storm": TreePalm,
  "canyon-storm": Mountain,
  "other-events": Star,
  "zombie-siege": Skull,
  "data-management": Database,
  "unmatched-names": UserCog,
  "video-upload": Upload,
  "video-queue": ClipboardCheck,
  "video-processors": UserCog,
  "alliance-settings": Settings,
  account: Settings,
  settings: Settings,
  allianceSettings: Settings,
  team: UserCog,
  "admin-portal": Shield,
  "discord-bot-guide": Bot,
  "discord-train-guide": LifeBuoy,
  "open-ashed": ExternalLink,
};

export function navPageIcon(pageId: string): LucideIcon | undefined {
  return NAV_PAGE_ICONS[pageId];
}
