#!/usr/bin/env bash
# sessionStart hook: dry-run git prune and inject a short debt report.
#
# Fail-open: any error returns empty JSON so agent startup is never blocked.
# Also writes .cursor/git-prune-status.md (gitignored via .cursor/*) so agents
# can still Read the report if sessionStart additional_context is dropped.
#
# See: scripts/git-prune.sh, .cursor/rules/agent-git-hygiene.mdc

set -u

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PRUNE_SCRIPT="${ROOT_DIR}/scripts/git-prune.sh"
STATUS_FILE="${ROOT_DIR}/.cursor/git-prune-status.md"

emit_empty() {
  printf '%s\n' '{}'
  exit 0
}

# Consume stdin (sessionStart payload).
input="$(cat || true)"

# Skip background agents — they should not pay the fetch cost on every spawn.
if command -v python3 >/dev/null 2>&1; then
  if printf '%s' "${input}" | python3 -c 'import json,sys
try:
    data = json.load(sys.stdin)
except json.JSONDecodeError:
    sys.exit(1)
sys.exit(0 if data.get("is_background_agent") is True else 1)' 2>/dev/null; then
    emit_empty
  fi
fi

if [[ ! -x "${PRUNE_SCRIPT}" ]]; then
  emit_empty
fi

if ! command -v python3 >/dev/null 2>&1; then
  emit_empty
fi

cd "${ROOT_DIR}" || emit_empty

# Dry-run with worktrees; compact = summary + machine trailer only.
report="$("${PRUNE_SCRIPT}" --worktrees --compact 2>/dev/null)" || emit_empty

branches="$(printf '%s\n' "${report}" | awk -F= '/^GIT_PRUNE_BRANCHES=/{print $2; exit}')"
worktrees="$(printf '%s\n' "${report}" | awk -F= '/^GIT_PRUNE_WORKTREES=/{print $2; exit}')"
dirty="$(printf '%s\n' "${report}" | awk -F= '/^GIT_PRUNE_SKIPPED_DIRTY=/{print $2; exit}')"

branches="${branches:-0}"
worktrees="${worktrees:-0}"
dirty="${dirty:-0}"

# Always refresh the sidecar status file (local-only; under gitignored .cursor/*).
mkdir -p "${ROOT_DIR}/.cursor" 2>/dev/null || true
{
  printf '%s\n' "# Git prune status"
  printf '%s\n' ""
  printf '%s\n' "Generated by \`.cursor/hooks/git-prune-session-start.sh\` (dry-run)."
  printf '%s\n' ""
  printf '%s\n' "| Metric | Count |"
  printf '%s\n' "| --- | ---: |"
  printf '%s\n' "| Branches safe to delete (gone upstream) | ${branches} |"
  printf '%s\n' "| Clean stale worktrees | ${worktrees} |"
  printf '%s\n' "| Skipped dirty worktrees | ${dirty} |"
  printf '%s\n' ""
  if [[ "${branches}" -eq 0 && "${worktrees}" -eq 0 ]]; then
    printf '%s\n' "No prune candidates right now."
  else
    printf '%s\n' "To clean up (maintainer approval for \`--apply\`):"
    printf '%s\n' ""
    printf '%s\n' '```bash'
    printf '%s\n' "./scripts/git-prune.sh --worktrees"
    printf '%s\n' "./scripts/git-prune.sh --apply --worktrees"
    printf '%s\n' '```'
  fi
  printf '%s\n' ""
  printf '%s\n' "_Do not auto-apply. Dirty worktrees are never deleted by the script._"
} > "${STATUS_FILE}" 2>/dev/null || true

if [[ "${branches}" -eq 0 && "${worktrees}" -eq 0 ]]; then
  context="Alliance HQ git hygiene: no stale gone-upstream branches or clean worktrees to prune."
else
  context="$(cat <<EOF
Alliance HQ git hygiene (sessionStart dry-run):
- ${branches} local branch(es) with deleted upstream are safe to delete
- ${worktrees} clean stale worktree(s) can be removed
- ${dirty} dirty worktree(s) were skipped

Read \`.cursor/git-prune-status.md\` for the table. Dry-run first:
\`./scripts/git-prune.sh --worktrees\`
Apply only with maintainer approval:
\`./scripts/git-prune.sh --apply --worktrees\`
Do not auto-delete dirty worktrees.
EOF
)"
fi

# Emit JSON via python3 (no jq dependency). Keep values as strings for env.
ALLIANCE_HQ_GIT_PRUNE_BRANCHES="${branches}" \
ALLIANCE_HQ_GIT_PRUNE_WORKTREES="${worktrees}" \
ALLIANCE_HQ_GIT_PRUNE_SKIPPED_DIRTY="${dirty}" \
ALLIANCE_HQ_GIT_PRUNE_CONTEXT="${context}" \
python3 - <<'PY'
import json, os
print(json.dumps({
  "env": {
    "ALLIANCE_HQ_GIT_PRUNE_BRANCHES": os.environ.get("ALLIANCE_HQ_GIT_PRUNE_BRANCHES", "0"),
    "ALLIANCE_HQ_GIT_PRUNE_WORKTREES": os.environ.get("ALLIANCE_HQ_GIT_PRUNE_WORKTREES", "0"),
    "ALLIANCE_HQ_GIT_PRUNE_SKIPPED_DIRTY": os.environ.get("ALLIANCE_HQ_GIT_PRUNE_SKIPPED_DIRTY", "0"),
  },
  "additional_context": os.environ.get("ALLIANCE_HQ_GIT_PRUNE_CONTEXT", ""),
}))
PY
